CREATE TABLE IF NOT EXISTS Person (
id int NOT NULL PRIMARY KEY,
firstName VARCHAR( 255) NOT NULL,
lastName VARCHAR(255) NOT NULL,
phoneNumber int NULL UNIQUE);


CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
firstName VARCHAR( 255) NOT NULL,
lastName VARCHAR(255) NOT NULL,
email VARCHAR(255) NULL UNIQUE,
phoneNumber int NULL UNIQUE);